### ISSUE TITLE
Dates

### ISSUE THREAD

**Issue by MichaelFreitasBR** [yianni-ververis/SenseUI-Slider#1]
Yianni Hello !

I USED SenseUI - Slider , great !

I have a question.

Does not work with dates ? DD/MM/YYYY

**Comment by yianni-ververis** [comment]
No, for now works only with numbers. I will try and change it soon

**Comment by MichaelFreitasBR** [comment]
Thanks for the feedback.

2016-07-05 12:09 GMT-03:00 Yianni Ververis notifications@github.com:

**Comment by singhdinesh** [comment]
Hi @yianni-ververis ,

I hope everything is well.
Did you update the extension for handling dates?

Thanks,
Dinesh

**Comment by yianni-ververis** [comment]
Hello,

No I have not worked on this extension for a  while.
