### ISSUE TITLE
SenseUI-Slider not functioning properly with Qlik Sense 3.0

### ISSUE THREAD

**Issue by hbuffum** [yianni-ververis/SenseUI-Slider#2]
I used  the SenseUI-Slider in an app I developed on a Qlik Server that was just upgraded from 2.24 to 3.0.  Under 2.24 the slider worked very nicely.  Since the upgrade, the slider buttons do not hold their positions.  Once the selection is made, the buttons jump back to the ends of the slider bar.  Is this a known issue?  Is there an update to this extension that is more compatible with 3.0?  Thanks.

**Comment by LucaG90** [comment]
Hi,
I have the same problem...can you help me? 

Thanks!

**Comment by yianni-ververis** [comment]
I am sorry I did not commit the last changes!

Please download the new version now.
